### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.PluggableAuthService#9]
Depends on:

- [x] #8 Make ZServer an optional dependency
- [x] zopefoundation/Products.PluginRegistry#3
- [x] zopefoundation/Products.GenericSetup#47
- [x] port this package: #14
- [x] partly revert b2df036
